### ISSUE TITLE
How to reproduce the benchmark results of Anna cluster?

### ISSUE THREAD

**Issue by catherine917** [hydro-project/cluster#25]
Hello,
Currently, I am trying to benchmark the Anna cluster. I set up Anna cluster on AWS by reusing the python script `create_cluster.py`. In the experiment, the cluster includes one routing node, 64 YCSB instances, while varying the number of memory nodes to test the throughput. Each server node is r4.2xlarge instance. The experiment runs a read-modify-write, uniform distribution YCSB workload.  Since the YCSB can't support Anna's test, I am using JNI to wrap the CPP client of Anna and send the requests to the cluster.  The testing result is below. According to the [paper](https://dsf.berkeley.edu/jmh/papers/anna_ieee18.pdf), I cannot get similar results. If I did something wrong, please correct me. 
![result](https://user-images.githubusercontent.com/8065961/85483952-6b018500-b5f8-11ea-9860-1f58f95afccc.PNG)
anna-base.yml
```yml
ebs: /ebs
capacities: # in GB
  memory-cap: 45 
  ebs-cap: 256
threads:
  memory: 4
  ebs: 4
  routing: 4
  benchmark: 4
replication:
  memory: 1
  ebs: 0
  minimum: 1
  local: 1
policy:
  elasticity: false
  selective-rep: false
  tiering: false
```
On the other hand, to generate enough requests to saturate the server, I oblige many YCSB instances. From the figure below,  I set up Anna cluster with two memory nodes and one routing node, but 64 YCSB instances and 40 threads for each YCSB instance. I think it is weird, and I am wondering how do you generate enough requests for the server by using YCSB client? If I put the YCSB client instances out of the cluster, how does the client communicate with the server?
![Capture](https://user-images.githubusercontent.com/8065961/85484364-478b0a00-b5f9-11ea-8de1-7386fa5da0a8.PNG)

Thanks and BR,
Catherine
